get http://localhost:5000/customers

###

get http://localhost:5000/customers/1

###

post http://localhost:5000/customers
content-type: application/json

{ "name": "jack" }

###

delete http://localhost:5000/customers/11